# Very Smart Analyzer Configuration

# Network settings
network:
  port: 8545
  chain_id: 1337
  data_dir: "network_data"
  accounts: 10
  block_time: 1
  gas_limit: 8000000

# AI settings
ai:
  model: "gpt-4"
  max_tokens: 4000
  temperature: 0.1
  timeout: 30

# Fuzz testing settings
fuzzer:
  default_iterations: 100
  max_gas_limit: 5000000
  timeout_per_test: 30

# Analysis settings
analyzer:
  enable_ai_analysis: true
  enable_fuzz_testing: true
  enable_execution_testing: true
  max_analysis_time: 300

# Reporting settings
reporter:
  output_dir: "reports"
  generate_json: true
  generate_text: true
  include_evidence: true

# Logging settings
logging:
  level: "info"
  format: "text"
  output: "stdout" 